export const errorsName = {
  CREATE_ERROR: "Error al crear",
  READ_ERROR: "Error al leer",
  UPDATE_ERROR: "Error al actualizar",
  DELETE_ERROR: "Error al eliminar",
  BAD_REQUEST: "Peticion incorrecta",
  NOT_FOUND: "No encontrado",
  INTERNAL_SERVER_ERROR: "Error interno del servidor",
  UNAUTHORIZED: "No autorizado",
  FORBIDDEN: "Prohibido",
  CONFLICT: "Conflicto",
  UNPROCESSABLE_ENTITY: "Entidad no procesable",
  TOO_MANY_REQUESTS: "Demasiadas peticiones",
  SERVICE_UNAVAILABLE: "Servicio no disponible",
  GATEWAY_TIMEOUT: "Tiempo de espera agotado",
  NETWORK_CONNECT_TIMEOUT_ERROR: "Tiempo de espera agotado",
  NETWORK_CONNECT_ERROR: "Error de conexión",
  NETWORK_DOWNLOAD_TIMEOUT_ERROR: "Tiempo de espera agotado",
  NETWORK_DOWNLOAD_ERROR: "Error de descarga",
  NETWORK_ERROR: "Error de red",
  VALIDATION_ERROR: "Error de validación",
  AUTHENTICATION_ERROR_MESSAGE: "Error de autenticación",
}

export const errorsMessage = {
  CREATE_ERROR: "Ocurrio un error al intentar crear el recurso",
  READ_ERROR: "Ocurrio un error al intentar leer el recurso",
  UPDATE_ERROR: "Ocurrio un error al intentar actualizar el recurso",
  DELETE_ERROR: "Ocurrio un error al intentar eliminar el recurso",
  AUTHENTICATION_ERROR_MESSAGE:
    "Ocurrio un error al intentar autenticar el usuario, verifique sus credenciales",
}

export const errorsCause = {
  AUTHENTICATION_ERROR_CAUSE: "Causa de usuario no autenticado",
  AUTHORIZATION_ERROR_CAUSE: "Causa de usuario no autorizado",
  PRODUCT_ERROR_CAUSE: "Causa de error en producto",
  USER_ERROR_CAUSE: "Causa de error en usuario",
  ORDER_ERROR_CAUSE: "Causa de error en orden",
  PAYMENT_ERROR_CAUSE: "Causa de error en pago",
  SHIPPING_ERROR_CAUSE: "Causa de error en envio",
  CART_ERROR_CAUSE: "Causa de error en carrito",
  REVIEW_ERROR_CAUSE: "Causa de error en review",
  CATEGORY_ERROR_CAUSE: "Causa de error en categoria",
  BRAND_ERROR_CAUSE: "Causa de error en marca",
  IMAGE_ERROR_CAUSE: "Causa de error en imagen",
  ADDRESS_ERROR_CAUSE: "Causa de error en direccion",
  COUPON_ERROR_CAUSE: "Causa de error en cupon",
  PAYMENT_METHOD_ERROR_CAUSE: "Causa de error en metodo de pago",
}
